import { ComponentType } from './types';

export const SAMPLE_DATA: Partial<Record<ComponentType, Record<string, any>>> = {
  [ComponentType.FIREWALL]: {
    deviceName: 'FW-CORP-01',
    model: 'Palo Alto PA-820',
    license: 'Threat Prevention Bundle',
    licenseExpiry: '2025-10-20',
    warranty: '2025-10-20',
    ipWan: '203.0.113.5',
    ipLan: '10.1.1.1',
    speed: '1 Gbps',
    ports: 8,
    firmware: '10.2.3',
    location: 'MDF Closet, 1st Floor',
  },
  [ComponentType.ROUTER]: {
    deviceName: 'RTR-EDGE-01',
    model: 'Cisco 4331',
    provider: 'Cisco',
    warranty: '2026-05-15',
    ipWan: '198.51.100.2',
    ipLan: '10.1.1.2',
    speed: '1 Gbps',
    ports: 3,
    firmware: '17.3.2',
    location: 'MDF Closet, 1st Floor',
  },
  [ComponentType.LOAD_BALANCER]: {
    model: 'F5 BIG-IP i2600',
    provider: 'F5 Networks',
    usagePeriod: '2022-2025',
    ipWan1: '203.0.113.10',
    ipWan2: '203.0.113.11',
    ipLan: '10.2.1.1',
    method: 'Round Robin',
    speed: '5 Gbps',
    ports: 4,
    firmware: '16.1.2',
    location: 'Data Center, Rack 5, U21',
  },
  [ComponentType.INTERNET]: {
    provider: 'Viettel',
    circuitId: 'FTTH-12345XYZ',
    contactInfo: 'support@viettel.vn - 18008098',
    ipWan: '123.30.140.21',
    credentials: 'user: admin / pass: ******',
  },
  [ComponentType.SWITCH]: {
    deviceName: 'SW-ACCESS-01',
    model: 'Cisco Catalyst 9200L',
    provider: 'Cisco',
    usagePeriod: '2023-2028',
    ip: '10.1.1.3',
    speed: '1 Gbps',
    ports: 48,
    firmware: '17.3.5',
    location: 'IDF Closet, 2nd Floor',
  },
  [ComponentType.VPN]: {
    systemName: 'Remote Access VPN',
    configDevice: 'FW-CORP-01',
    ipLan: '10.10.0.0/24',
    ipWanDialIn: 'vpn.its.com.vn',
    ipWanDialOut: 'N/A',
    presharedKey: '************',
    protocol: 'IKEv2/IPsec',
    localNetwork: '10.1.1.0/24',
    remoteNetwork: 'Any',
    encryption: 'AES-256-GCM',
    connectedSite: 'Remote Users',
  },
  [ComponentType.WIFI_AP]: {
    deviceName: 'AP-OFFICE-01',
    model: 'UniFi U6 Pro',
    provider: 'Ubiquiti',
    usagePeriod: '2023-2027',
    ipLink: '10.1.1.10',
    credentials: 'admin / *****',
    ssid: 'ITS-Office-WiFi',
    channel: 'Auto',
    frequency: '2.4Ghz/5.0Ghz',
    location: '2nd Floor, Open Area',
  },
  [ComponentType.IP_PBX]: {
    systemName: 'ITS VoIP System',
    provider: '3CX',
    ipWan: '198.51.100.5',
    servicePackage: 'Pro - 16 Calls',
    registeredPhones: '50',
    usagePeriod: 'Annual Subscription',
  },
  [ComponentType.PHYSICAL_SERVER]: {
    deviceName: 'SRV-DC-01',
    provider: 'Dell',
    usagePeriod: '2021-2026',
    model: 'PowerEdge R740',
    config: '2x Xeon Silver, 128GB RAM, 8x 1.2TB SAS RAID-10',
    ip: '10.2.1.10',
    os: 'VMware ESXi 7.0',
    role: 'Virtualization Host',
    location: 'Data Center, Rack 2, U15',
  },
  [ComponentType.VIRTUAL_SERVER]: {
    deviceName: 'VM-AD-01',
    hostMachine: 'SRV-DC-01',
    platform: 'VMware ESXi 7.0',
    ip: '10.2.2.5',
    config: '4 vCPU, 16GB RAM, 100GB Disk',
    os: 'Windows Server 2022',
    role: 'Active Directory, DNS, DHCP',
  },
  [ComponentType.CLOUD_SERVER]: {
    deviceName: 'Web-App-Prod-01',
    provider: 'Amazon Web Services (AWS)',
    servicePackage: 'EC2 - t3.large',
    usagePeriod: 'Pay-as-you-go',
    signupEmail: 'devops@its.com.vn',
    ipWan: '34.201.10.15',
    ipLan: '172.31.5.20',
    config: '2 vCPU, 8GB RAM, 120GB SSD',
    os: 'Ubuntu 22.04 LTS',
    role: 'Web Application Server',
  },
  [ComponentType.NVR]: {
    deviceName: 'NVR-SECURITY-01',
    model: 'Hikvision DS-7732NI-I4',
    provider: 'Hikvision',
    usagePeriod: '2022-2027',
    ip: '10.1.5.10',
    ports: '80, 554, 8000',
    accessLink: 'http://10.1.5.10',
    credentials: 'admin / ****',
    location: 'Security Room',
  },
  [ComponentType.UPS]: {
    deviceName: 'UPS-DC-RACK2',
    model: 'APC Smart-UPS 3000VA',
    provider: 'Schneider Electric',
    usagePeriod: '2021-2025',
    capacity: '2700W / 3000VA',
    ip: '10.2.1.5',
    accessLink: 'http://10.2.1.5',
    connectedDevices: 'SRV-DC-01, SW-CORE-01',
    alertEmail: 'it.alerts@its.com.vn',
    location: 'Data Center, Rack 2, U42',
  },
  [ComponentType.NAS]: {
    deviceName: 'NAS-FILES-01',
    model: 'Synology DS923+',
    provider: 'Synology',
    warranty: '2026-08-01',
    ipPort: '10.1.3.10:5001',
    config: '4x 4TB SATA HDD RAID-5, 32GB RAM',
    os: 'Synology DSM 7.2',
    location: 'MDF Closet, 1st Floor',
  },
  [ComponentType.DESKTOP]: {
    model: 'Dell OptiPlex 7000',
    provider: 'Dell',
    usagePeriod: '2023-2026',
    config: 'Core i7, 16GB RAM, 512GB NVMe SSD',
    ip: '10.1.2.101',
    os: 'Windows 11 Pro',
    userAccount: 'nv.an',
    location: 'Desk 101, Sales Dept',
  },
  [ComponentType.LAPTOP]: {
    model: 'MacBook Pro 14"',
    provider: 'Apple',
    usagePeriod: '2023-2026',
    config: 'M2 Pro, 16GB RAM, 512GB SSD',
    ip: '10.1.2.105',
    os: 'macOS Sonoma',
    userAccount: 'vt.binh',
    location: 'Desk 201, Design Dept',
  },
  [ComponentType.PRINTER]: {
    model: 'HP LaserJet Pro M428fdn',
    provider: 'HP',
    usagePeriod: '2022-2027',
    ip: '10.1.1.20',
    connection: 'Lan',
    location: '1st Floor, Copy Room',
  },
  [ComponentType.SCANNER]: {
    model: 'Fujitsu fi-8170',
    provider: 'Fujitsu',
    usagePeriod: '2023-2028',
    ip: '10.1.1.21',
    connection: 'Lan',
    location: '2nd Floor, Accounting Dept',
  },
  [ComponentType.USER_INFO]: {
    fullName: 'Nguyễn Văn An',
    department: 'Kinh doanh',
    title: 'Nhân viên kinh doanh',
    manager: 'Trần Thị Bình',
    phone: '0901234567',
    pcName: 'DESKTOP-NVAN',
    account: 'nv.an',
    email: 'an.nguyen@its.com.vn',
    permissions: 'CRM Access, Sales Share Drive',
    software: 'MS Office 365, MISA CRM',
  },
};
